Set up artillery
Abee-Petco/will-proxy pull request #1
Opened 2020-09-29 20:24 UTC by WDHudson

I refactored some of the code and added an artillery testing script.

2020-09-29 20:55 UTC, LachelleF approved these changes
Cool to see an artillery implementation. :+1:

2020-10-03 05:27 UTC, LesliePajuelo requested changes
api key!

2020-10-03 05:27 UTC, LesliePajuelo commented on newrelic.js
> +  license_key: '739d9ab4aef302b2a8c010fbaa519cea8e6fNRAL',
@WDHudson invalidate your key with new relic! untrack this file and gitignore it

2020-10-03 05:27 UTC, LesliePajuelo commented on package.json
>    "homepage": "https://github.com/PetToyCo/nick-proxy-server#readme",
👍

2020-10-03 05:27 UTC, LesliePajuelo commented on package.json
> +    "serve-static": "^1.14.1"
what's wrong with express.static?

2020-10-06 13:26 UTC, merged